version: "3.8"
services:
  db:
    image: mysql:9.1.0
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: api
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db